kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-node
  namespace: kube-system
spec:
  template:
    spec:
      initContainers:
        - name: install-cni
          image: ${CALICO_CNI_IMAGE}
          imagePullPolicy: IfNotPresent
        - name: flexvol-driver
          image: calico/pod2daemon-flexvol:${CALICO_VERSION_TAG}
      containers:
        - name: calico-node
          image: calico/node:${CALICO_VERSION_TAG}
          env:
            - name: NODENAME
              value: ""
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CALICO_BGP_LOGSEVERITYSCREEN
              value: info
            - name: CLUSTER_TYPE
              value: "k8s,bgp"
            - name: CALICO_ROUTER_ID
              value: "hash"
            - name: CALICO_IPV4POOL_IPIP
              value: ""
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: CALICO_IPV4POOL_IPIP
            - name: FELIX_IPV6SUPPORT
              value: ""
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: FELIX_IPV6SUPPORT
            - name: CALICO_IPV4POOL_NAT_OUTGOING
              value: ""
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: CALICO_IPV4POOL_NAT_OUTGOING
            - name: CALICO_IPV4POOL_VXLAN
              value: ""
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: CALICO_IPV4POOL_VXLAN
            - name: FELIX_IPINIPMTU
              value: ""
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: veth_mtu
            - name: CALICO_DISABLE_FILE_LOGGING
              value: "true"
            - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
              value: "ACCEPT"
            - name: FELIX_LOGSEVERITYSCREEN
              value: "info"
            - name: FELIX_HEALTHENABLED
              value: "true"
          envFrom:
          - configMapRef:
              name: calico-config