---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multinet-monitor-deployment
  namespace: calico-vpp-dataplane
spec:
  template:
    spec:
      containers:
        - name: multinet-monitor
          image: ${CALICO_VPP_IMAGE}
          command: ["/bin/multinet-monitor"]
          imagePullPolicy: ${IMAGE_PULL_POLICY}
