kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-vpp-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: calico-node
          # command:
          #   - bash
          #   - "-c"
          #   - sleep infinity
          volumeMounts:
            - name: repo-root
              mountPath: /home/hostuser/vpp-dataplane
              readOnly: true
            - name: api-proxy-binary
              mountPath: /bin/felix-api-proxy
              readOnly: true
            - name: agent-binary
              mountPath: /bin/calico-vpp-agent
              readOnly: true
        - name: vpp
          env:
            - name: CALICO_LOG_LEVEL
              value: debug
          volumeMounts:
            - name: vpp-root
              mountPath: /home/hostuser/vpp
              readOnly: true
            - name: repo-root
              mountPath: /home/hostuser/vpp-dataplane
              readOnly: true
      volumes:
        # Used to put the latest binaries in the containers (dev images) without rebuilding images in testing
        - name: repo-root
          hostPath:
            type: Directory
            path: /host-repo
        - name: api-proxy-binary
          hostPath:
            type: File
            path: /host-repo/calico-vpp-agent/cmd/felix-api-proxy
        - name: agent-binary
          hostPath:
            type: File
            path: /host-repo/calico-vpp-agent/cmd/calico-vpp-agent
        - name: vpp-root
          hostPath:
            type: Directory
            path: /host-repo/vpp-manager/vpp_build

