// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// source: /Users/nskrzypc/wrk/vpp/build-root/install-vpp-native/vpp/share/vpp/api/core/ip_neighbor.api.json

/*
Package ip_neighbor is a generated VPP binary API for 'ip_neighbor' module.

It consists of:
	 11 enums
	  7 aliases
	  7 types
	  1 union
	 15 messages
	  7 services
*/
package ip_neighbor

import (
	"bytes"
	"context"
	"io"
	"strconv"

	api "git.fd.io/govpp.git/api"
	struc "github.com/lunixbochs/struc"
)

const (
	// ModuleName is the name of this module.
	ModuleName = "ip_neighbor"
	// APIVersion is the API version of this module.
	APIVersion = "1.0.0"
	// VersionCrc is the CRC of this module.
	VersionCrc = 0xe6512b94
)

// AddressFamily represents VPP binary API enum 'address_family'.
type AddressFamily uint8

const (
	ADDRESS_IP4 AddressFamily = 0
	ADDRESS_IP6 AddressFamily = 1
)

var AddressFamily_name = map[uint8]string{
	0: "ADDRESS_IP4",
	1: "ADDRESS_IP6",
}

var AddressFamily_value = map[string]uint8{
	"ADDRESS_IP4": 0,
	"ADDRESS_IP6": 1,
}

func (x AddressFamily) String() string {
	s, ok := AddressFamily_name[uint8(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// IfStatusFlags represents VPP binary API enum 'if_status_flags'.
type IfStatusFlags uint32

const (
	IF_STATUS_API_FLAG_ADMIN_UP IfStatusFlags = 1
	IF_STATUS_API_FLAG_LINK_UP  IfStatusFlags = 2
)

var IfStatusFlags_name = map[uint32]string{
	1: "IF_STATUS_API_FLAG_ADMIN_UP",
	2: "IF_STATUS_API_FLAG_LINK_UP",
}

var IfStatusFlags_value = map[string]uint32{
	"IF_STATUS_API_FLAG_ADMIN_UP": 1,
	"IF_STATUS_API_FLAG_LINK_UP":  2,
}

func (x IfStatusFlags) String() string {
	s, ok := IfStatusFlags_name[uint32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// IfType represents VPP binary API enum 'if_type'.
type IfType uint32

const (
	IF_API_TYPE_HARDWARE IfType = 0
	IF_API_TYPE_SUB      IfType = 1
	IF_API_TYPE_P2P      IfType = 2
	IF_API_TYPE_PIPE     IfType = 3
)

var IfType_name = map[uint32]string{
	0: "IF_API_TYPE_HARDWARE",
	1: "IF_API_TYPE_SUB",
	2: "IF_API_TYPE_P2P",
	3: "IF_API_TYPE_PIPE",
}

var IfType_value = map[string]uint32{
	"IF_API_TYPE_HARDWARE": 0,
	"IF_API_TYPE_SUB":      1,
	"IF_API_TYPE_P2P":      2,
	"IF_API_TYPE_PIPE":     3,
}

func (x IfType) String() string {
	s, ok := IfType_name[uint32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// IPDscp represents VPP binary API enum 'ip_dscp'.
type IPDscp uint8

const (
	IP_API_DSCP_CS0  IPDscp = 0
	IP_API_DSCP_CS1  IPDscp = 8
	IP_API_DSCP_AF11 IPDscp = 10
	IP_API_DSCP_AF12 IPDscp = 12
	IP_API_DSCP_AF13 IPDscp = 14
	IP_API_DSCP_CS2  IPDscp = 16
	IP_API_DSCP_AF21 IPDscp = 18
	IP_API_DSCP_AF22 IPDscp = 20
	IP_API_DSCP_AF23 IPDscp = 22
	IP_API_DSCP_CS3  IPDscp = 24
	IP_API_DSCP_AF31 IPDscp = 26
	IP_API_DSCP_AF32 IPDscp = 28
	IP_API_DSCP_AF33 IPDscp = 30
	IP_API_DSCP_CS4  IPDscp = 32
	IP_API_DSCP_AF41 IPDscp = 34
	IP_API_DSCP_AF42 IPDscp = 36
	IP_API_DSCP_AF43 IPDscp = 38
	IP_API_DSCP_CS5  IPDscp = 40
	IP_API_DSCP_EF   IPDscp = 46
	IP_API_DSCP_CS6  IPDscp = 48
	IP_API_DSCP_CS7  IPDscp = 50
)

var IPDscp_name = map[uint8]string{
	0:  "IP_API_DSCP_CS0",
	8:  "IP_API_DSCP_CS1",
	10: "IP_API_DSCP_AF11",
	12: "IP_API_DSCP_AF12",
	14: "IP_API_DSCP_AF13",
	16: "IP_API_DSCP_CS2",
	18: "IP_API_DSCP_AF21",
	20: "IP_API_DSCP_AF22",
	22: "IP_API_DSCP_AF23",
	24: "IP_API_DSCP_CS3",
	26: "IP_API_DSCP_AF31",
	28: "IP_API_DSCP_AF32",
	30: "IP_API_DSCP_AF33",
	32: "IP_API_DSCP_CS4",
	34: "IP_API_DSCP_AF41",
	36: "IP_API_DSCP_AF42",
	38: "IP_API_DSCP_AF43",
	40: "IP_API_DSCP_CS5",
	46: "IP_API_DSCP_EF",
	48: "IP_API_DSCP_CS6",
	50: "IP_API_DSCP_CS7",
}

var IPDscp_value = map[string]uint8{
	"IP_API_DSCP_CS0":  0,
	"IP_API_DSCP_CS1":  8,
	"IP_API_DSCP_AF11": 10,
	"IP_API_DSCP_AF12": 12,
	"IP_API_DSCP_AF13": 14,
	"IP_API_DSCP_CS2":  16,
	"IP_API_DSCP_AF21": 18,
	"IP_API_DSCP_AF22": 20,
	"IP_API_DSCP_AF23": 22,
	"IP_API_DSCP_CS3":  24,
	"IP_API_DSCP_AF31": 26,
	"IP_API_DSCP_AF32": 28,
	"IP_API_DSCP_AF33": 30,
	"IP_API_DSCP_CS4":  32,
	"IP_API_DSCP_AF41": 34,
	"IP_API_DSCP_AF42": 36,
	"IP_API_DSCP_AF43": 38,
	"IP_API_DSCP_CS5":  40,
	"IP_API_DSCP_EF":   46,
	"IP_API_DSCP_CS6":  48,
	"IP_API_DSCP_CS7":  50,
}

func (x IPDscp) String() string {
	s, ok := IPDscp_name[uint8(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// IPEcn represents VPP binary API enum 'ip_ecn'.
type IPEcn uint8

const (
	IP_API_ECN_NONE IPEcn = 0
	IP_API_ECN_ECT0 IPEcn = 1
	IP_API_ECN_ECT1 IPEcn = 2
	IP_API_ECN_CE   IPEcn = 3
)

var IPEcn_name = map[uint8]string{
	0: "IP_API_ECN_NONE",
	1: "IP_API_ECN_ECT0",
	2: "IP_API_ECN_ECT1",
	3: "IP_API_ECN_CE",
}

var IPEcn_value = map[string]uint8{
	"IP_API_ECN_NONE": 0,
	"IP_API_ECN_ECT0": 1,
	"IP_API_ECN_ECT1": 2,
	"IP_API_ECN_CE":   3,
}

func (x IPEcn) String() string {
	s, ok := IPEcn_name[uint8(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// IPNeighborFlags represents VPP binary API enum 'ip_neighbor_flags'.
type IPNeighborFlags uint8

const (
	IP_API_NEIGHBOR_FLAG_NONE         IPNeighborFlags = 0
	IP_API_NEIGHBOR_FLAG_STATIC       IPNeighborFlags = 1
	IP_API_NEIGHBOR_FLAG_NO_FIB_ENTRY IPNeighborFlags = 2
)

var IPNeighborFlags_name = map[uint8]string{
	0: "IP_API_NEIGHBOR_FLAG_NONE",
	1: "IP_API_NEIGHBOR_FLAG_STATIC",
	2: "IP_API_NEIGHBOR_FLAG_NO_FIB_ENTRY",
}

var IPNeighborFlags_value = map[string]uint8{
	"IP_API_NEIGHBOR_FLAG_NONE":         0,
	"IP_API_NEIGHBOR_FLAG_STATIC":       1,
	"IP_API_NEIGHBOR_FLAG_NO_FIB_ENTRY": 2,
}

func (x IPNeighborFlags) String() string {
	s, ok := IPNeighborFlags_name[uint8(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// IPProto represents VPP binary API enum 'ip_proto'.
type IPProto uint8

const (
	IP_API_PROTO_HOPOPT   IPProto = 0
	IP_API_PROTO_ICMP     IPProto = 1
	IP_API_PROTO_IGMP     IPProto = 2
	IP_API_PROTO_TCP      IPProto = 6
	IP_API_PROTO_UDP      IPProto = 17
	IP_API_PROTO_GRE      IPProto = 47
	IP_API_PROTO_ESP      IPProto = 50
	IP_API_PROTO_AH       IPProto = 51
	IP_API_PROTO_ICMP6    IPProto = 58
	IP_API_PROTO_EIGRP    IPProto = 88
	IP_API_PROTO_OSPF     IPProto = 89
	IP_API_PROTO_SCTP     IPProto = 132
	IP_API_PROTO_RESERVED IPProto = 255
)

var IPProto_name = map[uint8]string{
	0:   "IP_API_PROTO_HOPOPT",
	1:   "IP_API_PROTO_ICMP",
	2:   "IP_API_PROTO_IGMP",
	6:   "IP_API_PROTO_TCP",
	17:  "IP_API_PROTO_UDP",
	47:  "IP_API_PROTO_GRE",
	50:  "IP_API_PROTO_ESP",
	51:  "IP_API_PROTO_AH",
	58:  "IP_API_PROTO_ICMP6",
	88:  "IP_API_PROTO_EIGRP",
	89:  "IP_API_PROTO_OSPF",
	132: "IP_API_PROTO_SCTP",
	255: "IP_API_PROTO_RESERVED",
}

var IPProto_value = map[string]uint8{
	"IP_API_PROTO_HOPOPT":   0,
	"IP_API_PROTO_ICMP":     1,
	"IP_API_PROTO_IGMP":     2,
	"IP_API_PROTO_TCP":      6,
	"IP_API_PROTO_UDP":      17,
	"IP_API_PROTO_GRE":      47,
	"IP_API_PROTO_ESP":      50,
	"IP_API_PROTO_AH":       51,
	"IP_API_PROTO_ICMP6":    58,
	"IP_API_PROTO_EIGRP":    88,
	"IP_API_PROTO_OSPF":     89,
	"IP_API_PROTO_SCTP":     132,
	"IP_API_PROTO_RESERVED": 255,
}

func (x IPProto) String() string {
	s, ok := IPProto_name[uint8(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// LinkDuplex represents VPP binary API enum 'link_duplex'.
type LinkDuplex uint32

const (
	LINK_DUPLEX_API_UNKNOWN LinkDuplex = 0
	LINK_DUPLEX_API_HALF    LinkDuplex = 1
	LINK_DUPLEX_API_FULL    LinkDuplex = 2
)

var LinkDuplex_name = map[uint32]string{
	0: "LINK_DUPLEX_API_UNKNOWN",
	1: "LINK_DUPLEX_API_HALF",
	2: "LINK_DUPLEX_API_FULL",
}

var LinkDuplex_value = map[string]uint32{
	"LINK_DUPLEX_API_UNKNOWN": 0,
	"LINK_DUPLEX_API_HALF":    1,
	"LINK_DUPLEX_API_FULL":    2,
}

func (x LinkDuplex) String() string {
	s, ok := LinkDuplex_name[uint32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// MtuProto represents VPP binary API enum 'mtu_proto'.
type MtuProto uint32

const (
	MTU_PROTO_API_L3   MtuProto = 0
	MTU_PROTO_API_IP4  MtuProto = 1
	MTU_PROTO_API_IP6  MtuProto = 2
	MTU_PROTO_API_MPLS MtuProto = 3
)

var MtuProto_name = map[uint32]string{
	0: "MTU_PROTO_API_L3",
	1: "MTU_PROTO_API_IP4",
	2: "MTU_PROTO_API_IP6",
	3: "MTU_PROTO_API_MPLS",
}

var MtuProto_value = map[string]uint32{
	"MTU_PROTO_API_L3":   0,
	"MTU_PROTO_API_IP4":  1,
	"MTU_PROTO_API_IP6":  2,
	"MTU_PROTO_API_MPLS": 3,
}

func (x MtuProto) String() string {
	s, ok := MtuProto_name[uint32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// RxMode represents VPP binary API enum 'rx_mode'.
type RxMode uint32

const (
	RX_MODE_API_UNKNOWN   RxMode = 0
	RX_MODE_API_POLLING   RxMode = 1
	RX_MODE_API_INTERRUPT RxMode = 2
	RX_MODE_API_ADAPTIVE  RxMode = 3
	RX_MODE_API_DEFAULT   RxMode = 4
)

var RxMode_name = map[uint32]string{
	0: "RX_MODE_API_UNKNOWN",
	1: "RX_MODE_API_POLLING",
	2: "RX_MODE_API_INTERRUPT",
	3: "RX_MODE_API_ADAPTIVE",
	4: "RX_MODE_API_DEFAULT",
}

var RxMode_value = map[string]uint32{
	"RX_MODE_API_UNKNOWN":   0,
	"RX_MODE_API_POLLING":   1,
	"RX_MODE_API_INTERRUPT": 2,
	"RX_MODE_API_ADAPTIVE":  3,
	"RX_MODE_API_DEFAULT":   4,
}

func (x RxMode) String() string {
	s, ok := RxMode_name[uint32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// SubIfFlags represents VPP binary API enum 'sub_if_flags'.
type SubIfFlags uint32

const (
	SUB_IF_API_FLAG_NO_TAGS           SubIfFlags = 1
	SUB_IF_API_FLAG_ONE_TAG           SubIfFlags = 2
	SUB_IF_API_FLAG_TWO_TAGS          SubIfFlags = 4
	SUB_IF_API_FLAG_DOT1AD            SubIfFlags = 8
	SUB_IF_API_FLAG_EXACT_MATCH       SubIfFlags = 16
	SUB_IF_API_FLAG_DEFAULT           SubIfFlags = 32
	SUB_IF_API_FLAG_OUTER_VLAN_ID_ANY SubIfFlags = 64
	SUB_IF_API_FLAG_INNER_VLAN_ID_ANY SubIfFlags = 128
	SUB_IF_API_FLAG_MASK_VNET         SubIfFlags = 254
	SUB_IF_API_FLAG_DOT1AH            SubIfFlags = 256
)

var SubIfFlags_name = map[uint32]string{
	1:   "SUB_IF_API_FLAG_NO_TAGS",
	2:   "SUB_IF_API_FLAG_ONE_TAG",
	4:   "SUB_IF_API_FLAG_TWO_TAGS",
	8:   "SUB_IF_API_FLAG_DOT1AD",
	16:  "SUB_IF_API_FLAG_EXACT_MATCH",
	32:  "SUB_IF_API_FLAG_DEFAULT",
	64:  "SUB_IF_API_FLAG_OUTER_VLAN_ID_ANY",
	128: "SUB_IF_API_FLAG_INNER_VLAN_ID_ANY",
	254: "SUB_IF_API_FLAG_MASK_VNET",
	256: "SUB_IF_API_FLAG_DOT1AH",
}

var SubIfFlags_value = map[string]uint32{
	"SUB_IF_API_FLAG_NO_TAGS":           1,
	"SUB_IF_API_FLAG_ONE_TAG":           2,
	"SUB_IF_API_FLAG_TWO_TAGS":          4,
	"SUB_IF_API_FLAG_DOT1AD":            8,
	"SUB_IF_API_FLAG_EXACT_MATCH":       16,
	"SUB_IF_API_FLAG_DEFAULT":           32,
	"SUB_IF_API_FLAG_OUTER_VLAN_ID_ANY": 64,
	"SUB_IF_API_FLAG_INNER_VLAN_ID_ANY": 128,
	"SUB_IF_API_FLAG_MASK_VNET":         254,
	"SUB_IF_API_FLAG_DOT1AH":            256,
}

func (x SubIfFlags) String() string {
	s, ok := SubIfFlags_name[uint32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}

// AddressWithPrefix represents VPP binary API alias 'address_with_prefix'.
type AddressWithPrefix Prefix

// InterfaceIndex represents VPP binary API alias 'interface_index'.
type InterfaceIndex uint32

// IP4Address represents VPP binary API alias 'ip4_address'.
type IP4Address [4]uint8

// IP4AddressWithPrefix represents VPP binary API alias 'ip4_address_with_prefix'.
type IP4AddressWithPrefix IP4Prefix

// IP6Address represents VPP binary API alias 'ip6_address'.
type IP6Address [16]uint8

// IP6AddressWithPrefix represents VPP binary API alias 'ip6_address_with_prefix'.
type IP6AddressWithPrefix IP6Prefix

// MacAddress represents VPP binary API alias 'mac_address'.
type MacAddress [6]uint8

// Address represents VPP binary API type 'address'.
type Address struct {
	Af AddressFamily
	Un AddressUnion
}

func (*Address) GetTypeName() string { return "address" }

// IP4Prefix represents VPP binary API type 'ip4_prefix'.
type IP4Prefix struct {
	Address IP4Address
	Len     uint8
}

func (*IP4Prefix) GetTypeName() string { return "ip4_prefix" }

// IP6Prefix represents VPP binary API type 'ip6_prefix'.
type IP6Prefix struct {
	Address IP6Address
	Len     uint8
}

func (*IP6Prefix) GetTypeName() string { return "ip6_prefix" }

// IPNeighbor represents VPP binary API type 'ip_neighbor'.
type IPNeighbor struct {
	SwIfIndex  InterfaceIndex
	Flags      IPNeighborFlags
	MacAddress MacAddress
	IPAddress  Address
}

func (*IPNeighbor) GetTypeName() string { return "ip_neighbor" }

// Mprefix represents VPP binary API type 'mprefix'.
type Mprefix struct {
	Af               AddressFamily
	GrpAddressLength uint16
	GrpAddress       AddressUnion
	SrcAddress       AddressUnion
}

func (*Mprefix) GetTypeName() string { return "mprefix" }

// Prefix represents VPP binary API type 'prefix'.
type Prefix struct {
	Address Address
	Len     uint8
}

func (*Prefix) GetTypeName() string { return "prefix" }

// PrefixMatcher represents VPP binary API type 'prefix_matcher'.
type PrefixMatcher struct {
	Le uint8
	Ge uint8
}

func (*PrefixMatcher) GetTypeName() string { return "prefix_matcher" }

// AddressUnion represents VPP binary API union 'address_union'.
type AddressUnion struct {
	XXX_UnionData [16]byte
}

func (*AddressUnion) GetTypeName() string { return "address_union" }

func AddressUnionIP4(a IP4Address) (u AddressUnion) {
	u.SetIP4(a)
	return
}
func (u *AddressUnion) SetIP4(a IP4Address) {
	var b = new(bytes.Buffer)
	if err := struc.Pack(b, &a); err != nil {
		return
	}
	copy(u.XXX_UnionData[:], b.Bytes())
}
func (u *AddressUnion) GetIP4() (a IP4Address) {
	var b = bytes.NewReader(u.XXX_UnionData[:])
	struc.Unpack(b, &a)
	return
}

func AddressUnionIP6(a IP6Address) (u AddressUnion) {
	u.SetIP6(a)
	return
}
func (u *AddressUnion) SetIP6(a IP6Address) {
	var b = new(bytes.Buffer)
	if err := struc.Pack(b, &a); err != nil {
		return
	}
	copy(u.XXX_UnionData[:], b.Bytes())
}
func (u *AddressUnion) GetIP6() (a IP6Address) {
	var b = bytes.NewReader(u.XXX_UnionData[:])
	struc.Unpack(b, &a)
	return
}

// IPNeighborAddDel represents VPP binary API message 'ip_neighbor_add_del'.
type IPNeighborAddDel struct {
	IsAdd    bool
	Neighbor IPNeighbor
}

func (m *IPNeighborAddDel) Reset()                        { *m = IPNeighborAddDel{} }
func (*IPNeighborAddDel) GetMessageName() string          { return "ip_neighbor_add_del" }
func (*IPNeighborAddDel) GetCrcString() string            { return "105518b6" }
func (*IPNeighborAddDel) GetMessageType() api.MessageType { return api.RequestMessage }

// IPNeighborAddDelReply represents VPP binary API message 'ip_neighbor_add_del_reply'.
type IPNeighborAddDelReply struct {
	Retval     int32
	StatsIndex uint32
}

func (m *IPNeighborAddDelReply) Reset()                        { *m = IPNeighborAddDelReply{} }
func (*IPNeighborAddDelReply) GetMessageName() string          { return "ip_neighbor_add_del_reply" }
func (*IPNeighborAddDelReply) GetCrcString() string            { return "1992deab" }
func (*IPNeighborAddDelReply) GetMessageType() api.MessageType { return api.ReplyMessage }

// IPNeighborConfig represents VPP binary API message 'ip_neighbor_config'.
type IPNeighborConfig struct {
	Af        AddressFamily
	MaxNumber uint32
	MaxAge    uint32
	Recycle   bool
}

func (m *IPNeighborConfig) Reset()                        { *m = IPNeighborConfig{} }
func (*IPNeighborConfig) GetMessageName() string          { return "ip_neighbor_config" }
func (*IPNeighborConfig) GetCrcString() string            { return "f4a5cf44" }
func (*IPNeighborConfig) GetMessageType() api.MessageType { return api.RequestMessage }

// IPNeighborConfigReply represents VPP binary API message 'ip_neighbor_config_reply'.
type IPNeighborConfigReply struct {
	Retval int32
}

func (m *IPNeighborConfigReply) Reset()                        { *m = IPNeighborConfigReply{} }
func (*IPNeighborConfigReply) GetMessageName() string          { return "ip_neighbor_config_reply" }
func (*IPNeighborConfigReply) GetCrcString() string            { return "e8d4e804" }
func (*IPNeighborConfigReply) GetMessageType() api.MessageType { return api.ReplyMessage }

// IPNeighborDetails represents VPP binary API message 'ip_neighbor_details'.
type IPNeighborDetails struct {
	Age      float64
	Neighbor IPNeighbor
}

func (m *IPNeighborDetails) Reset()                        { *m = IPNeighborDetails{} }
func (*IPNeighborDetails) GetMessageName() string          { return "ip_neighbor_details" }
func (*IPNeighborDetails) GetCrcString() string            { return "870e80b9" }
func (*IPNeighborDetails) GetMessageType() api.MessageType { return api.ReplyMessage }

// IPNeighborDump represents VPP binary API message 'ip_neighbor_dump'.
type IPNeighborDump struct {
	SwIfIndex InterfaceIndex
	Af        AddressFamily
}

func (m *IPNeighborDump) Reset()                        { *m = IPNeighborDump{} }
func (*IPNeighborDump) GetMessageName() string          { return "ip_neighbor_dump" }
func (*IPNeighborDump) GetCrcString() string            { return "cd831298" }
func (*IPNeighborDump) GetMessageType() api.MessageType { return api.RequestMessage }

// IPNeighborEvent represents VPP binary API message 'ip_neighbor_event'.
type IPNeighborEvent struct {
	PID      uint32
	Neighbor IPNeighbor
}

func (m *IPNeighborEvent) Reset()                        { *m = IPNeighborEvent{} }
func (*IPNeighborEvent) GetMessageName() string          { return "ip_neighbor_event" }
func (*IPNeighborEvent) GetCrcString() string            { return "83933131" }
func (*IPNeighborEvent) GetMessageType() api.MessageType { return api.EventMessage }

// IPNeighborFlush represents VPP binary API message 'ip_neighbor_flush'.
type IPNeighborFlush struct {
	Af        AddressFamily
	SwIfIndex InterfaceIndex
}

func (m *IPNeighborFlush) Reset()                        { *m = IPNeighborFlush{} }
func (*IPNeighborFlush) GetMessageName() string          { return "ip_neighbor_flush" }
func (*IPNeighborFlush) GetCrcString() string            { return "16aa35d2" }
func (*IPNeighborFlush) GetMessageType() api.MessageType { return api.RequestMessage }

// IPNeighborFlushReply represents VPP binary API message 'ip_neighbor_flush_reply'.
type IPNeighborFlushReply struct {
	Retval int32
}

func (m *IPNeighborFlushReply) Reset()                        { *m = IPNeighborFlushReply{} }
func (*IPNeighborFlushReply) GetMessageName() string          { return "ip_neighbor_flush_reply" }
func (*IPNeighborFlushReply) GetCrcString() string            { return "e8d4e804" }
func (*IPNeighborFlushReply) GetMessageType() api.MessageType { return api.ReplyMessage }

// IPNeighborReplaceBegin represents VPP binary API message 'ip_neighbor_replace_begin'.
type IPNeighborReplaceBegin struct{}

func (m *IPNeighborReplaceBegin) Reset()                        { *m = IPNeighborReplaceBegin{} }
func (*IPNeighborReplaceBegin) GetMessageName() string          { return "ip_neighbor_replace_begin" }
func (*IPNeighborReplaceBegin) GetCrcString() string            { return "51077d14" }
func (*IPNeighborReplaceBegin) GetMessageType() api.MessageType { return api.RequestMessage }

// IPNeighborReplaceBeginReply represents VPP binary API message 'ip_neighbor_replace_begin_reply'.
type IPNeighborReplaceBeginReply struct {
	Retval int32
}

func (m *IPNeighborReplaceBeginReply) Reset()                        { *m = IPNeighborReplaceBeginReply{} }
func (*IPNeighborReplaceBeginReply) GetMessageName() string          { return "ip_neighbor_replace_begin_reply" }
func (*IPNeighborReplaceBeginReply) GetCrcString() string            { return "e8d4e804" }
func (*IPNeighborReplaceBeginReply) GetMessageType() api.MessageType { return api.ReplyMessage }

// IPNeighborReplaceEnd represents VPP binary API message 'ip_neighbor_replace_end'.
type IPNeighborReplaceEnd struct{}

func (m *IPNeighborReplaceEnd) Reset()                        { *m = IPNeighborReplaceEnd{} }
func (*IPNeighborReplaceEnd) GetMessageName() string          { return "ip_neighbor_replace_end" }
func (*IPNeighborReplaceEnd) GetCrcString() string            { return "51077d14" }
func (*IPNeighborReplaceEnd) GetMessageType() api.MessageType { return api.RequestMessage }

// IPNeighborReplaceEndReply represents VPP binary API message 'ip_neighbor_replace_end_reply'.
type IPNeighborReplaceEndReply struct {
	Retval int32
}

func (m *IPNeighborReplaceEndReply) Reset()                        { *m = IPNeighborReplaceEndReply{} }
func (*IPNeighborReplaceEndReply) GetMessageName() string          { return "ip_neighbor_replace_end_reply" }
func (*IPNeighborReplaceEndReply) GetCrcString() string            { return "e8d4e804" }
func (*IPNeighborReplaceEndReply) GetMessageType() api.MessageType { return api.ReplyMessage }

// WantIPNeighborEvents represents VPP binary API message 'want_ip_neighbor_events'.
type WantIPNeighborEvents struct {
	Enable    bool
	PID       uint32
	IP        Address
	SwIfIndex InterfaceIndex
}

func (m *WantIPNeighborEvents) Reset()                        { *m = WantIPNeighborEvents{} }
func (*WantIPNeighborEvents) GetMessageName() string          { return "want_ip_neighbor_events" }
func (*WantIPNeighborEvents) GetCrcString() string            { return "1a312870" }
func (*WantIPNeighborEvents) GetMessageType() api.MessageType { return api.RequestMessage }

// WantIPNeighborEventsReply represents VPP binary API message 'want_ip_neighbor_events_reply'.
type WantIPNeighborEventsReply struct {
	Retval int32
}

func (m *WantIPNeighborEventsReply) Reset()                        { *m = WantIPNeighborEventsReply{} }
func (*WantIPNeighborEventsReply) GetMessageName() string          { return "want_ip_neighbor_events_reply" }
func (*WantIPNeighborEventsReply) GetCrcString() string            { return "e8d4e804" }
func (*WantIPNeighborEventsReply) GetMessageType() api.MessageType { return api.ReplyMessage }

func init() {
	api.RegisterMessage((*IPNeighborAddDel)(nil), "ip_neighbor.IPNeighborAddDel")
	api.RegisterMessage((*IPNeighborAddDelReply)(nil), "ip_neighbor.IPNeighborAddDelReply")
	api.RegisterMessage((*IPNeighborConfig)(nil), "ip_neighbor.IPNeighborConfig")
	api.RegisterMessage((*IPNeighborConfigReply)(nil), "ip_neighbor.IPNeighborConfigReply")
	api.RegisterMessage((*IPNeighborDetails)(nil), "ip_neighbor.IPNeighborDetails")
	api.RegisterMessage((*IPNeighborDump)(nil), "ip_neighbor.IPNeighborDump")
	api.RegisterMessage((*IPNeighborEvent)(nil), "ip_neighbor.IPNeighborEvent")
	api.RegisterMessage((*IPNeighborFlush)(nil), "ip_neighbor.IPNeighborFlush")
	api.RegisterMessage((*IPNeighborFlushReply)(nil), "ip_neighbor.IPNeighborFlushReply")
	api.RegisterMessage((*IPNeighborReplaceBegin)(nil), "ip_neighbor.IPNeighborReplaceBegin")
	api.RegisterMessage((*IPNeighborReplaceBeginReply)(nil), "ip_neighbor.IPNeighborReplaceBeginReply")
	api.RegisterMessage((*IPNeighborReplaceEnd)(nil), "ip_neighbor.IPNeighborReplaceEnd")
	api.RegisterMessage((*IPNeighborReplaceEndReply)(nil), "ip_neighbor.IPNeighborReplaceEndReply")
	api.RegisterMessage((*WantIPNeighborEvents)(nil), "ip_neighbor.WantIPNeighborEvents")
	api.RegisterMessage((*WantIPNeighborEventsReply)(nil), "ip_neighbor.WantIPNeighborEventsReply")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*IPNeighborAddDel)(nil),
		(*IPNeighborAddDelReply)(nil),
		(*IPNeighborConfig)(nil),
		(*IPNeighborConfigReply)(nil),
		(*IPNeighborDetails)(nil),
		(*IPNeighborDump)(nil),
		(*IPNeighborEvent)(nil),
		(*IPNeighborFlush)(nil),
		(*IPNeighborFlushReply)(nil),
		(*IPNeighborReplaceBegin)(nil),
		(*IPNeighborReplaceBeginReply)(nil),
		(*IPNeighborReplaceEnd)(nil),
		(*IPNeighborReplaceEndReply)(nil),
		(*WantIPNeighborEvents)(nil),
		(*WantIPNeighborEventsReply)(nil),
	}
}

// RPCService represents RPC service API for ip_neighbor module.
type RPCService interface {
	DumpIPNeighbor(ctx context.Context, in *IPNeighborDump) (RPCService_DumpIPNeighborClient, error)
	IPNeighborAddDel(ctx context.Context, in *IPNeighborAddDel) (*IPNeighborAddDelReply, error)
	IPNeighborConfig(ctx context.Context, in *IPNeighborConfig) (*IPNeighborConfigReply, error)
	IPNeighborFlush(ctx context.Context, in *IPNeighborFlush) (*IPNeighborFlushReply, error)
	IPNeighborReplaceBegin(ctx context.Context, in *IPNeighborReplaceBegin) (*IPNeighborReplaceBeginReply, error)
	IPNeighborReplaceEnd(ctx context.Context, in *IPNeighborReplaceEnd) (*IPNeighborReplaceEndReply, error)
	WantIPNeighborEvents(ctx context.Context, in *WantIPNeighborEvents) (*WantIPNeighborEventsReply, error)
}

type serviceClient struct {
	ch api.Channel
}

func NewServiceClient(ch api.Channel) RPCService {
	return &serviceClient{ch}
}

func (c *serviceClient) DumpIPNeighbor(ctx context.Context, in *IPNeighborDump) (RPCService_DumpIPNeighborClient, error) {
	stream := c.ch.SendMultiRequest(in)
	x := &serviceClient_DumpIPNeighborClient{stream}
	return x, nil
}

type RPCService_DumpIPNeighborClient interface {
	Recv() (*IPNeighborDetails, error)
}

type serviceClient_DumpIPNeighborClient struct {
	api.MultiRequestCtx
}

func (c *serviceClient_DumpIPNeighborClient) Recv() (*IPNeighborDetails, error) {
	m := new(IPNeighborDetails)
	stop, err := c.MultiRequestCtx.ReceiveReply(m)
	if err != nil {
		return nil, err
	}
	if stop {
		return nil, io.EOF
	}
	return m, nil
}

func (c *serviceClient) IPNeighborAddDel(ctx context.Context, in *IPNeighborAddDel) (*IPNeighborAddDelReply, error) {
	out := new(IPNeighborAddDelReply)
	err := c.ch.SendRequest(in).ReceiveReply(out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) IPNeighborConfig(ctx context.Context, in *IPNeighborConfig) (*IPNeighborConfigReply, error) {
	out := new(IPNeighborConfigReply)
	err := c.ch.SendRequest(in).ReceiveReply(out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) IPNeighborFlush(ctx context.Context, in *IPNeighborFlush) (*IPNeighborFlushReply, error) {
	out := new(IPNeighborFlushReply)
	err := c.ch.SendRequest(in).ReceiveReply(out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) IPNeighborReplaceBegin(ctx context.Context, in *IPNeighborReplaceBegin) (*IPNeighborReplaceBeginReply, error) {
	out := new(IPNeighborReplaceBeginReply)
	err := c.ch.SendRequest(in).ReceiveReply(out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) IPNeighborReplaceEnd(ctx context.Context, in *IPNeighborReplaceEnd) (*IPNeighborReplaceEndReply, error) {
	out := new(IPNeighborReplaceEndReply)
	err := c.ch.SendRequest(in).ReceiveReply(out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) WantIPNeighborEvents(ctx context.Context, in *WantIPNeighborEvents) (*WantIPNeighborEventsReply, error) {
	out := new(WantIPNeighborEventsReply)
	err := c.ch.SendRequest(in).ReceiveReply(out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion1 // please upgrade the GoVPP api package

// Reference imports to suppress errors if they are not otherwise used.
var _ = api.RegisterMessage
var _ = bytes.NewBuffer
var _ = context.Background
var _ = io.Copy
var _ = strconv.Itoa
var _ = struc.Pack
