version: "2"
run:
  concurrency: 4
  tests: false
  allow-parallel-runners: false
output:
  formats:
    tab:
      path: stderr
      colors: false
linters:
  enable:
    - misspell
  settings:
    staticcheck:
      dot-import-whitelist:
        - "github.com/onsi/ginkgo"
        - "github.com/onsi/gomega"
      checks:
        - all
    errcheck:
      check-type-assertions: true
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    nolintlint:
      require-explanation: true
      require-specific: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
