apiVersion: v1
kind: Namespace
metadata:
  name: calico-vpp-dataplane
  annotations:
    openshift.io/node-selector: ""
  labels:
    name: calico-vpp-dataplane
    openshift.io/run-level: "0"
    security.openshift.io/scc.podSecurityLabelSync: "false"
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
