# -*- mode: ruby -*-

# Load the vagrantfile_common file to have all the variables & the config script
$vagrantfilecommon = File.expand_path('../../vagrantfiles/Vagrantfile_common', __FILE__)
NODE = 0 # Unused but required by the script
load $vagrantfilecommon

Vagrant.configure('2') do |config|
    config.vm.define :base_vm do |base_vm|
        base_vm.vm.box = "generic/ubuntu2204"
        base_vm.ssh.insert_key = false
        base_vm.vm.boot_timeout = 900

        base_vm.vm.provider :libvirt do |l|
            l.driver = "kvm"
            # l.disk_driver :discard => "unmap"
            l.default_prefix = CLUSTER_NAME + '_'
            l.cpus = MASTER_CPUS
            l.memory = MASTER_MEMORY_SIZE_GB * 1024
            l.machine_virtual_size = DISK_SIZE_GB
        end

        base_vm.vm.provision :shell, inline: $baseConfigScript
        
    end
end

