version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      golang: latest

  pre_build:
    commands:
      - CI_BUILD=1
      - echo Build started on `date`

      - docker --version
      - git config --global user.email "calicoci@cisco.com"
      - git config --global user.name "Calico CI"

      - echo "Logging to dockerhub"
      - docker login --username ${DOCKERHUB_USERNAME} --password=${DOCKERHUB_TOKEN} || true
      - ACCOUNT_ID="$(aws sts get-caller-identity --query "Account" --output text)"
      - >-
        aws ecr get-login-password --region $AWS_DEFAULT_REGION |
        docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - echo "Building dependencies image"
      - make builder-image

  build:
    commands:
      - make clean-vpp
      - make images

      # run linting and go tests
      - make mdlint
      - make ci-lint
      - make ci-test
      - make ci-cov

      # Publish image, even if they are not fine
      # as this helps reproducing
      - make push

      # Run integration tests (kind & e2e)
      - make kind
      - make test-e2e
      - make kind-rm-cluster

  post_build:
    commands:
      - echo Build completed on `date`
