version: 0.2

env:
  shell: bash

phases:
  pre_build:
    commands:
      - cd .ci
      - echo Build started on `date`

      - docker --version

      - echo "Logging to dockerhub"
      - docker login --username ${DOCKERHUB_USERNAME} --password=${DOCKERHUB_TOKEN} || true

      - echo "Building dependencies image"
      - make depend-image

  build:
    commands:
      - make go-check

  post_build:
    commands:
      - echo "Build complete"

      - echo Build completed on `date`
