version: 0.2

env:
  shell: bash

phases:
  pre_build:
    commands:
      - CI_BUILD=1
      - cd .ci
      - echo Build started on `date`

      - docker --version
      - make ci-install

      - echo "Logging to dockerhub"
      - docker login --username ${DOCKERHUB_USERNAME} --password=${DOCKERHUB_TOKEN} || true

      - echo "Building dependencies image"
      - make depend-image

  build:
    commands:
      - make go-check

      - make -C ../ images
      - docker images
      - make -C ../ run-integration-tests
      - make -C ../ push


  post_build:
    commands:
      - echo "Build complete"

      - echo Build completed on `date`
