kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-vpp-config
  namespace: calico-vpp-dataplane
data:  # Configuration template for VPP in EKS
  service_prefix: 10.100.0.0/16
  vpp_dataplane_interface: eth0
  vpp_uplink_driver: af_packet

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-vpp-node
  namespace: calico-vpp-dataplane
spec:
  template:
    spec:
      containers:
        - name: vpp
          env:
            - name: CALICOVPP_HOOK_BEFORE_VPP_RUN
              value: "echo 'sudo systemctl stop network ; sudo systemctl kill network' | chroot /host"
            - name: CALICOVPP_HOOK_VPP_RUNNING
              value: "echo 'sudo systemctl start network' | chroot /host"
            - name: CALICOVPP_HOOK_VPP_DONE_OK
              value: "echo 'sudo systemctl stop network ; sudo systemctl kill network ; sudo systemctl start network' | chroot /host"
            - name: CALICOVPP_HOOK_VPP_ERRORED
              value: "echo 'sudo systemctl stop network ; sudo systemctl kill network ; sudo systemctl start network' | chroot /host"
          volumeMounts:
            - mountPath: /host
              name: host-root
      volumes:
        - hostPath:
            path: /
          name: host-root
