kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-vpp-config
  namespace: calico-vpp-dataplane
data:  # Configuration template for VPP in EKS
  SERVICE_PREFIX: 10.100.0.0/16
  CALICOVPP_INTERFACES: |-
    {
      "maxPodIfSpec": {
        "rx": 10, "tx": 10, "rxqsz": 1024, "txqsz": 1024
      },
      "defaultPodIfSpec": {
        "rx": 1, "tx":1, "isl3": true
      },
      "vppHostTapSpec": {
        "rx": 1, "tx":1, "rxqsz": 1024, "txqsz": 1024, "isl3": false
      },
      "uplinkInterfaces": [
        {
          "interfaceName": "ens5",
          "vppDriver": "af_packet"
        }
      ]
    }
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: calico-vpp-node
  namespace: calico-vpp-dataplane
spec:
  template:
    spec:
      containers:
        - name: vpp
          env:
            - name: CALICOVPP_HOOK_VPP_RUNNING
              value: echo "sudo cp /usr/lib/systemd/network/80-ec2.network /etc/systemd/network/ens5.network; sudo sed -i 's/Driver=.*/Name=ens5/' /etc/systemd/network/ens5.network; sudo systemctl daemon-reload; sudo systemctl restart systemd-networkd" | chroot /host
            - name: CALICOVPP_HOOK_VPP_DONE_OK
              value: echo 'sudo rm /etc/systemd/network/ens5.network; systemctl daemon-reload; sudo systemctl restart systemd-networkd' | chroot /host
            - name: CALICOVPP_HOOK_VPP_ERRORED
              value: echo 'sudo rm /etc/systemd/network/ens5.network; systemctl daemon-reload; sudo systemctl restart systemd-networkd' | chroot /host
