// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: podinfo_api.proto

package grpcsrv

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Address structure describes a single instance of an address assigned to the pod
type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr    []byte `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	MaskLen int32  `protobuf:"varint,2,opt,name=mask_len,json=maskLen,proto3" json:"mask_len,omitempty"`
	IsIpv6  bool   `protobuf:"varint,3,opt,name=is_ipv6,json=isIpv6,proto3" json:"is_ipv6,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podinfo_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_podinfo_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_podinfo_api_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetAddr() []byte {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *Address) GetMaskLen() int32 {
	if x != nil {
		return x.MaskLen
	}
	return 0
}

func (x *Address) GetIsIpv6() bool {
	if x != nil {
		return x.IsIpv6
	}
	return false
}

// PodInfo structure describes information returning by gRPC server with details
// about requested pod
type PodInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableId  int32      `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	PortName string     `protobuf:"bytes,2,opt,name=port_name,json=portName,proto3" json:"port_name,omitempty"`
	PodAddr  []*Address `protobuf:"bytes,3,rep,name=pod_addr,json=podAddr,proto3" json:"pod_addr,omitempty"`
}

func (x *PodInfo) Reset() {
	*x = PodInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podinfo_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodInfo) ProtoMessage() {}

func (x *PodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_podinfo_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodInfo.ProtoReflect.Descriptor instead.
func (*PodInfo) Descriptor() ([]byte, []int) {
	return file_podinfo_api_proto_rawDescGZIP(), []int{1}
}

func (x *PodInfo) GetTableId() int32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *PodInfo) GetPortName() string {
	if x != nil {
		return x.PortName
	}
	return ""
}

func (x *PodInfo) GetPodAddr() []*Address {
	if x != nil {
		return x.PodAddr
	}
	return nil
}

// PodInfoReq structure describes information sent to gRPC server, it includes:
// request id - to track requests, namespace - pod's actual namespace,
// and pod id - the actual pod's UUID.
type PodInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqId     int32  `protobuf:"varint,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodId     string `protobuf:"bytes,3,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
}

func (x *PodInfoReq) Reset() {
	*x = PodInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podinfo_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodInfoReq) ProtoMessage() {}

func (x *PodInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_podinfo_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodInfoReq.ProtoReflect.Descriptor instead.
func (*PodInfoReq) Descriptor() ([]byte, []int) {
	return file_podinfo_api_proto_rawDescGZIP(), []int{2}
}

func (x *PodInfoReq) GetReqId() int32 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *PodInfoReq) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodInfoReq) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

// PodInfoRepl structure describes information returned by gRPC server to
// the requesting process.
// In case of a failure of getting requested pod's info, gRPC server returns
// a number error code and well as details error desccription.
type PodInfoRepl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodInfo   *PodInfo `protobuf:"bytes,1,opt,name=pod_info,json=podInfo,proto3" json:"pod_info,omitempty"`
	Err       int32    `protobuf:"varint,2,opt,name=err,proto3" json:"err,omitempty"`
	ErrDetail string   `protobuf:"bytes,3,opt,name=err_detail,json=errDetail,proto3" json:"err_detail,omitempty"`
}

func (x *PodInfoRepl) Reset() {
	*x = PodInfoRepl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_podinfo_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodInfoRepl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodInfoRepl) ProtoMessage() {}

func (x *PodInfoRepl) ProtoReflect() protoreflect.Message {
	mi := &file_podinfo_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodInfoRepl.ProtoReflect.Descriptor instead.
func (*PodInfoRepl) Descriptor() ([]byte, []int) {
	return file_podinfo_api_proto_rawDescGZIP(), []int{3}
}

func (x *PodInfoRepl) GetPodInfo() *PodInfo {
	if x != nil {
		return x.PodInfo
	}
	return nil
}

func (x *PodInfoRepl) GetErr() int32 {
	if x != nil {
		return x.Err
	}
	return 0
}

func (x *PodInfoRepl) GetErrDetail() string {
	if x != nil {
		return x.ErrDetail
	}
	return ""
}

var File_podinfo_api_proto protoreflect.FileDescriptor

var file_podinfo_api_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x6f, 0x64, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x72, 0x70, 0x63, 0x73, 0x72, 0x76, 0x22, 0x51, 0x0a, 0x07,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x6d,
	0x61, 0x73, 0x6b, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d,
	0x61, 0x73, 0x6b, 0x4c, 0x65, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x69, 0x70, 0x76,
	0x36, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x49, 0x70, 0x76, 0x36, 0x22,
	0x6e, 0x0a, 0x07, 0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x72, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x70, 0x6f, 0x64, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x70, 0x6f, 0x64, 0x41, 0x64, 0x64, 0x72, 0x22,
	0x58, 0x0a, 0x0a, 0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a,
	0x06, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72,
	0x65, 0x71, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x6f, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x6f, 0x64, 0x49, 0x64, 0x22, 0x6b, 0x0a, 0x0b, 0x50, 0x6f, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x12, 0x2b, 0x0a, 0x08, 0x70, 0x6f, 0x64, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x73, 0x72, 0x76, 0x2e, 0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x70, 0x6f,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x5f, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x32, 0x3e, 0x0a, 0x0a, 0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x53, 0x76, 0x63, 0x12, 0x30, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x13, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x50, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x1a, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x72, 0x76, 0x2e, 0x50, 0x6f, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_podinfo_api_proto_rawDescOnce sync.Once
	file_podinfo_api_proto_rawDescData = file_podinfo_api_proto_rawDesc
)

func file_podinfo_api_proto_rawDescGZIP() []byte {
	file_podinfo_api_proto_rawDescOnce.Do(func() {
		file_podinfo_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_podinfo_api_proto_rawDescData)
	})
	return file_podinfo_api_proto_rawDescData
}

var file_podinfo_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_podinfo_api_proto_goTypes = []interface{}{
	(*Address)(nil),     // 0: grpcsrv.Address
	(*PodInfo)(nil),     // 1: grpcsrv.PodInfo
	(*PodInfoReq)(nil),  // 2: grpcsrv.PodInfoReq
	(*PodInfoRepl)(nil), // 3: grpcsrv.PodInfoRepl
}
var file_podinfo_api_proto_depIdxs = []int32{
	0, // 0: grpcsrv.PodInfo.pod_addr:type_name -> grpcsrv.Address
	1, // 1: grpcsrv.PodInfoRepl.pod_info:type_name -> grpcsrv.PodInfo
	2, // 2: grpcsrv.PodInfoSvc.Get:input_type -> grpcsrv.PodInfoReq
	3, // 3: grpcsrv.PodInfoSvc.Get:output_type -> grpcsrv.PodInfoRepl
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_podinfo_api_proto_init() }
func file_podinfo_api_proto_init() {
	if File_podinfo_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_podinfo_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podinfo_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podinfo_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_podinfo_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodInfoRepl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_podinfo_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_podinfo_api_proto_goTypes,
		DependencyIndexes: file_podinfo_api_proto_depIdxs,
		MessageInfos:      file_podinfo_api_proto_msgTypes,
	}.Build()
	File_podinfo_api_proto = out.File
	file_podinfo_api_proto_rawDesc = nil
	file_podinfo_api_proto_goTypes = nil
	file_podinfo_api_proto_depIdxs = nil
}
