kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-vpp-config
  namespace: calico-vpp-dataplane
data:  # Configuration template for VPP in Kind
  SERVICE_PREFIX: 10.96.0.0/16
  CALICOVPP_INTERFACES: |-
    {
      "uplinkInterfaces": [
        {
          "interfaceName": "eth0",
          "vppDriver": "af_packet"
        }
      ]
    }
  CALICOVPP_INITIAL_CONFIG: |-
    {
      "vppStartupSleepSeconds": 1,
      "corePattern": "/var/lib/vpp/vppcore.%e.%p",
      "redirectToHostRules": [
        {
          "proto": "udp",
          "port": 53,
          "ip": "172.18.0.1"
        },
        {
          "proto": "tcp",
          "port": 53,
          "ip": "172.18.0.1"
        }
      ]
    }
