kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-vpp-config
  namespace: calico-vpp-dataplane
data:
  vpp_uplink_driver: ""
  vpp_config_template: |-
    unix {
      nodaemon
      full-coredump
      cli-listen /var/run/vpp/cli.sock
      pidfile /run/vpp/vpp.pid
      exec /etc/vpp/startup.exec
    }
    api-trace { on }
    cpu {
        workers 1
    }
    socksvr {
        socket-name /var/run/vpp/vpp-api.sock
    }
    plugins {
        plugin default { enable }
        plugin dpdk_plugin.so { disable }
        plugin calico_plugin.so { enable }
        plugin ping_plugin.so { disable }
    }
    buffers {
      buffers-per-numa 131072
    }
  CALICOVPP_INTERFACES: |-
    {
      "maxIfSpec": {
        "rx": 10, "tx":10
      },
      "defaultPodIfSpec": {
        "rx": 1, "tx":1, "rxqsz": 1024, "txqsz": 1024, "isl3": true, "rxMode": "polling"
      },
      "vppHostTapSpec": {
        "rx": 1, "tx":1, "rxqsz": 1024, "txqsz": 1024, "isl3": false, "rxMode": "polling"
      },
      "uplinkInterfaces": [
        {
          "isMain": true, "interface": "eth1", "rxMode": "polling"
        }
      ]
    }
